import type { Metadata } from 'next'
import { Geist_Mono, Lora } from 'next/font/google'
import './globals.css'
import Navbar from '@/component/shared/Navbar'
import { BookProvider } from '@/context/BooksContext'
import { ToastContainer } from 'react-toastify'
import Footer from '@/component/shared/Footer'

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// })

// const playfair = Playfair({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// })
const lora = Lora({
  variable: '--font-lora',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang='en'
      className={`${lora.className} ${geistMono.variable} h-full antialiased`}
    >
      <body className='min-h-screen flex flex-col'>
        <ToastContainer />

        <BookProvider>
          <Navbar />

          <main className='flex-1'>{children}</main>

          <Footer />
        </BookProvider>
      </body>
    </html>
  )
}
